import { existsSync, mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { Command } from "commander";
import pc from "picocolors";
import { DEFAULT_SPOOLIGNORE } from "@spool/shared";

/**
 * `spool init` — scaffolds the per-project opt-in for v0.3 file capture
 * (SPEC §7.1 + §10.3).
 *
 * Writes two files at the chosen root (defaults to cwd):
 *
 *   1. `.spool/config.toml` — the repo-level opt-in toggle. v0.3 file
 *      capture is OFF by default until the user runs this command;
 *      that's the local-first stance the spec calls out (§10.3, mirrors
 *      v0.2 §17). Without this file, FileChange rows still emit but
 *      with no blob refs, so the *fact* of an edit is recorded but the
 *      contents aren't.
 *
 *   2. `.spoolignore` — a user-editable copy of `DEFAULT_SPOOLIGNORE`,
 *      pre-populated so the user can see and tweak what gets filtered.
 *
 * Idempotent: existing files are left alone unless `--force` is passed.
 * The exit code distinguishes the three outcomes so CI can gate on it
 * (0 = scaffold created or already present, 2 = bad arg).
 */
export function registerInitCommand(program: Command): void {
  program
    .command("init [path]")
    .description(
      "Scaffold .spool/config.toml and .spoolignore for v0.3 file capture",
    )
    .option(
      "--force",
      "Overwrite existing files (default: leave existing files untouched)",
    )
    .option(
      "--quiet",
      "Suppress per-file output (still prints the final summary)",
    )
    .action(async (
      pathArg: string | undefined,
      opts: { force?: boolean; quiet?: boolean },
    ) => {
      const root = resolve(pathArg ?? process.cwd());
      if (!existsSync(root)) {
        console.error(pc.red(`spool init: target path does not exist: ${root}`));
        process.exit(2);
      }

      // Determine what to write. Each entry has a path + the contents
      // we'd produce on a fresh write. Existing-file logic lives at
      // the writeIfNeeded boundary below.
      const ignorePath = join(root, ".spoolignore");
      const configDir = join(root, ".spool");
      const configPath = join(configDir, "config.toml");

      mkdirSync(configDir, { recursive: true });

      const ignoreResult = await writeIfNeeded(
        ignorePath,
        renderSpoolignore(),
        opts.force === true,
      );
      const configResult = await writeIfNeeded(
        configPath,
        renderConfigToml(),
        opts.force === true,
      );

      if (!opts.quiet) {
        printFileResult(".spoolignore", ignorePath, ignoreResult);
        printFileResult(".spool/config.toml", configPath, configResult);
      }

      // Summary footer. Tells the user what to do next; the call-to-
      // action is the part that actually drives adoption.
      const allCreated =
        ignoreResult === "created" && configResult === "created";
      if (allCreated) {
        console.log(
          pc.bold(pc.green("\nspool init: scaffolded")) +
            pc.dim(" — v0.3 file capture is now on for this project."),
        );
      } else {
        console.log(
          pc.dim(
            "\nspool init: complete. Re-run with --force to regenerate existing files.",
          ),
        );
      }
      console.log(
        pc.dim(
          "  edit .spoolignore to tune what gets captured\n" +
            "  see `spool files <run-id>` after your next Claude Code session",
        ),
      );
    });
}

type WriteResult = "created" | "skipped" | "overwritten";

async function writeIfNeeded(
  path: string,
  contents: string,
  force: boolean,
): Promise<WriteResult> {
  const present = existsSync(path);
  if (present && !force) return "skipped";
  await writeFile(path, contents, "utf-8");
  return present ? "overwritten" : "created";
}

function printFileResult(label: string, path: string, result: WriteResult): void {
  const tag =
    result === "created"
      ? pc.green("created")
      : result === "overwritten"
        ? pc.yellow("overwrote")
        : pc.dim("kept existing");
  console.log(`  ${tag}  ${pc.cyan(label)} ${pc.dim(`(${path})`)}`);
}

/**
 * Render the default `.spoolignore`. We ship one line per pattern,
 * grouped by the same sections used in `DEFAULT_SPOOLIGNORE`, so the
 * file is editable by humans. Comments explain each section so users
 * understand what they're inheriting.
 */
function renderSpoolignore(): string {
  return `# .spoolignore — paths Spool excludes from file capture (v0.3+).
# Same syntax subset as .gitignore. First match wins; no negation in v0.3.
# Generated by \`spool init\`. Edit freely.

# Build artifacts
node_modules/
dist/
build/
.next/
target/
.cache/

# Language-specific
.venv/
__pycache__/
*.pyc

# Version control internals
.git/objects/
.git/logs/

# Editor / OS
.DS_Store
.idea/
.vscode/

# Coverage / tooling
coverage/
.nyc_output/

# Sensitive by default — paired with redaction rules in the collector
.env
.env.*
*.pem
*.key
id_rsa*
id_ed25519*
credentials.json
.aws/
.kube/config
`;
}

/**
 * The opt-in `.spool/config.toml`. v0.3 reads `[capture.files].enabled`
 * to gate FileChange blob capture; the other keys are wired through
 * in v0.4 (the spec leaves them defined for forward-compat).
 */
function renderConfigToml(): string {
  return `# .spool/config.toml — per-project Spool configuration.
# v0.3 reads [capture.files] only; later milestones add more sections.

[capture.files]
# When false, FileChange rows still record the *fact* of an edit but
# leave before/after blob refs unset (partial_diff = true). Set true to
# capture the bytes Claude Code / Codex / the SDK / the proxy actually
# wrote. Off-by-default because capturing code from a random \`cd\`
# deserves deliberation.
enabled = true

# Glob patterns. Empty include = "everything not ignored."
include = []
exclude = []

# Files larger than this are excluded from the baseline manifest and
# from full-snapshot FileChange capture. Defaults to 5 MB; the
# patch_text on the row still records the edit when applicable. Raise
# this for repos with large generated assets you actually want
# captured.
max_file_size_bytes = 5_242_880

# Binary detection strategy. "null-byte-heuristic" matches PR 1's
# isProbablyText (NUL in first 8 KB ⇒ binary). "magic-bytes" is
# scheduled for v0.4 — it parses file magic for higher precision.
binary_detection = "null-byte-heuristic"
`;
}

// Re-export for the index registration.
export { DEFAULT_SPOOLIGNORE };
